### PR TITLE
feat(avatar): add bao-avatar component.

### LINKED ISSUE #49: Create the Avatar component
Link to specs : https://confluence.montreal.ca/pages/viewpage.action?pageId=142017894
Please reachout to @gregpetit to groom the component.

### PR DESCRIPTION
**Pull request by MaudeLaflamme**
close #49

Signed-off-by: Maude LAFLAMME <maude.laflamme@montreal.ca>

avatar_1

avatar_2

### CODE REVIEW

**Comment by MaudeLaflamme** [comment]
@gregpetit Je n'étais pas sûre de la structure que devrait avoir le storybook, puisque le input "color" ne s'applique qu'à un seul type de contenu de l'avatar. Laisse-moi savoir si ce serait mieux autrement.

**Review by OlivierAlbertini — APPROVED** [review]
LGTM 💯 

nit: I don't know if in the spec it's like that, but I would change color-1, color-2, color-3, color-number by color-name, e.g color-pink, color-red, color-blue.

**Comment by MaudeLaflamme** [comment]
@OlivierAlbertini The colors' IDs were not defined in the specs, I agree that "color-name" is more user-friendly, I'll change that.

**Review by gregpetit — COMMENTED** [review]
@MaudeLaflamme 
All good except for the fact there is an issue with the SVG I sent you. I sent you the right one.
Also tested with a screenreader and all good in term of accessibility.

**Comment by OlivierAlbertini** [comment]
> @OlivierAlbertini @gregpetit visual changes also need to be accepted on Chromatic, in order for all checks to complete.

Done! 🚀

**Pull request merged**
